import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//

import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CRUD NextJS and NestJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
  
}: Readonly<{
  children: React.ReactNode;
  
}>) {
  return (
    <html lang="en" className="bg-zinc-300 dark:bg-zinc-900">
      <head></head>
      <body className="bg-gray-100" >
        <Navbar  />
        <div >{children}</div>
        </body>
    </html>
  );
}
